trigger:
- main

stages:
- stage: DeployToDev
  jobs:
  - deployment: DevDeployment
    environment: DevEnv
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: |
              echo "Listing repo contents:"
              ls -la
            displayName: '🔍 List files on agent'
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'AzureRMServiceConnection'
              subscriptionId: '7c37d74b-a989-4857-bc3d-7dec86170754'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'DevopsRG'
              location: 'centralus'
              templateLocation: 'Linked artifact'
              csmFile: 'azuretemplate.json'
              csmParametersFile: 'azureparameters.json'
              deploymentMode: 'Incremental'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
